const PET_COLLECTIONS = {
  USERS: "users",
  GAME_CONFIG: "gameConfig",
};

const PET_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  PET_NOT_FOUND: "PET_NOT_FOUND",
  PET_ALREADY_SELECTED: "PET_ALREADY_SELECTED",
  INVALID_PET_TYPE: "INVALID_PET_TYPE",
  INVALID_ACTION: "INVALID_ACTION",
  PET_TOO_FULL: "PET_TOO_FULL",
  PET_TOO_TIRED: "PET_TOO_TIRED",
  PET_NOT_READY: "PET_NOT_READY",
  GAME_CONFIG_NOT_FOUND: "GAME_CONFIG_NOT_FOUND",
  INVALID_GAME_CONFIG: "INVALID_GAME_CONFIG",
  CONCURRENT_UPDATE_DETECTED: "CONCURRENT_UPDATE_DETECTED",
  REQUEST_DUPLICATED: "REQUEST_DUPLICATED",
  ACTION_COOLDOWN_ACTIVE: "ACTION_COOLDOWN_ACTIVE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

const PET_MOOD_PRIORITY = ["sick", "sleepy", "hungry", "sad", "normal", "happy"];

const PET_ACTIONS = {
  SELECT: "select",
  FEED: "feed",
  PLAY: "play",
  SLEEP: "sleep",
  GET: "get",
  SYNC: "sync",
};

module.exports = {
  PET_ACTIONS,
  PET_COLLECTIONS,
  PET_ERROR_CODES,
  PET_MOOD_PRIORITY,
};
